### PR TITLE
Added Optional Animation Curve, fixes #2

### LINKED ISSUE #2: Option to Supply Custom Animation Curve
It would be nice if we could supply a custom animation curve for the widget :) It can look a bit dull having it be linearly interpolated all the time. Great widget though!

### PR DESCRIPTION
**Pull request by EriKWDev**
Added optional parameter "curve" so that a custom Curve can be supplied
to the widget for cleaner animations.

Also updated the default duration to better match the default
linearToEaseOut curve.

### CODE REVIEW

**Comment by EriKWDev** [comment]
ping @aliyigitbireroglu

**Comment by EriKWDev** [comment]
Is there anything that should be changed? :) @aliyigitbireroglu 
Perhaps add the curve as an optional parameter in the README example...

**Comment by aliyigitbireroglu** [comment]
Thank you, it looks great. Sorry for the delay, I have been on vacations. I will also push this version to pub.dev.

**Comment by aliyigitbireroglu** [comment]
The new version is now released. Thank you for your contribution🙂

**Comment by EriKWDev** [comment]
Nice! NP.

**Pull request merged**
